apiVersion: 1
groups:
    - orgId: 1
      name: Alerting group
      folder: Shard events
      interval: 2m
      rules:
        - uid: f915a647-f598-4e63-98f5-cd076d2c5450
          title: Shard events
          condition: D
          data:
            - refId: Disconnects over 10m
              relativeTimeRange:
                from: 600
                to: 0
              datasourceUid: PBFA97CFB590B2093
              model:
                datasource:
                    type: prometheus
                    uid: PBFA97CFB590B2093
                editorMode: code
                exemplar: true
                expr: sum by (exported_instance) (rate(bot_shard_disconnected{exported_instance=~"(prod-1|prod-2|prod-3|prod-4|prod-5)"}[$__rate_interval]) * 60)
                format: time_series
                instant: false
                interval: ""
                intervalFactor: 1
                intervalMs: 15000
                legendFormat: '{{exported_instance}} disconnect'
                maxDataPoints: 43200
                range: true
                refId: Disconnects over 10m
            - refId: D
              relativeTimeRange:
                from: 600
                to: 0
              datasourceUid: __expr__
              model:
                conditions:
                    - evaluator:
                        params:
                            - 3
                        type: gt
                      operator:
                        type: and
                      query:
                        params:
                            - D
                      reducer:
                        params: []
                        type: last
                      type: query
                datasource:
                    type: __expr__
                    uid: __expr__
                expression: Average
                intervalMs: 1000
                maxDataPoints: 43200
                refId: D
                type: threshold
            - refId: Average
              relativeTimeRange:
                from: 600
                to: 0
              datasourceUid: __expr__
              model:
                conditions:
                    - evaluator:
                        params:
                            - 0
                            - 0
                        type: gt
                      operator:
                        type: and
                      query:
                        params: []
                      reducer:
                        params: []
                        type: avg
                      type: query
                datasource:
                    name: Expression
                    type: __expr__
                    uid: __expr__
                expression: Disconnects over 10m
                intervalMs: 1000
                maxDataPoints: 43200
                reducer: mean
                refId: Average
                settings:
                    mode: dropNN
                type: reduce
          dashboardUid: zyAf4i4Zz
          panelId: 59
          noDataState: NoData
          execErrState: Error
          for: 10m
          annotations:
            __dashboardUid__: zyAf4i4Zz
            __panelId__: "59"
            description: ""
            runbook_url: ""
            summary: Shard disconnects are occurring too frequently
          labels:
            "": ""
          isPaused: false
